import {
  Sunrise,
  Dumbbell,
  BookOpen,
  Wallet,
  Laptop,
  GlassWater,
  PhoneOff,
  NotebookPen,
  Snowflake,
  CheckCircle,
  Target,
  Heart,
  Star,
  Zap,
  Coffee,
  Moon,
  Music,
  Palette,
  Users,
  Trophy,
  Flame,
  Leaf,
  Brain,
  Bike,
  Camera,
  Clock,
  Compass,
  Feather,
  Gift,
  Globe,
  Headphones,
  Home,
  Lightbulb,
  MapPin,
  Mic,
  Mountain,
  Pencil,
  Phone,
  Plane,
  Salad,
  Shield,
  ShoppingBag,
  Smile,
  Sun,
  Umbrella,
  Watch,
  Waves,
  Wind,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  sunrise: Sunrise,
  dumbbell: Dumbbell,
  book: BookOpen,
  wallet: Wallet,
  laptop: Laptop,
  "glass-water": GlassWater,
  "phone-off": PhoneOff,
  notebook: NotebookPen,
  snowflake: Snowflake,
  check: CheckCircle,
  target: Target,
  heart: Heart,
  star: Star,
  zap: Zap,
  coffee: Coffee,
  moon: Moon,
  music: Music,
  palette: Palette,
  users: Users,
  trophy: Trophy,
  flame: Flame,
  leaf: Leaf,
  brain: Brain,
  bike: Bike,
  camera: Camera,
  clock: Clock,
  compass: Compass,
  feather: Feather,
  gift: Gift,
  globe: Globe,
  headphones: Headphones,
  home: Home,
  lightbulb: Lightbulb,
  "map-pin": MapPin,
  mic: Mic,
  mountain: Mountain,
  pencil: Pencil,
  phone: Phone,
  plane: Plane,
  salad: Salad,
  shield: Shield,
  "shopping-bag": ShoppingBag,
  smile: Smile,
  sun: Sun,
  umbrella: Umbrella,
  watch: Watch,
  waves: Waves,
  wind: Wind,
};

interface HabitIconProps {
  icon?: string;
  emoji?: string;
  className?: string;
}

export function HabitIcon({ icon, emoji, className = "w-4 h-4" }: HabitIconProps) {
  const iconKey = icon || emoji;
  const Icon = iconKey && iconMap[iconKey] ? iconMap[iconKey] : Target;
  return <Icon className={className} />;
}

export const habitIconOptions = Object.keys(iconMap);
